
#application.yml file
server:
  port: 8001
spring:
  application:
    name: API-GATEWAY
  main:
    allow-bean-definition-overriding: true


  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/Productservice/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.0.101:8761/eureka

